title: "Emil Paul"
description: "Scalable systems • Applied AI/ML • Cloud"
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

header_pages:
  - index.md
  - projects.md
  - about.md
  - links.md
  - contact.md
  
